### ISSUE TITLE
수박게임 만들기 TODO

### ISSUE THREAD

**Issue by GHeeJeon** [my-ggott-games/watermelon-game-embitta#3]
- [x] Webstorm 설치
- [x] 수박게임 오리지널 플레이해보기
- [x] 수박게임 코드 클론(포크)하기
- [x] 수박게임 제작의도(덕질, 기념일, 친목도모 등) 선정
- [x] 이미지 고르기
- [x] favicon 설정
- [x] 사운드 변경
- [x] 배포
